default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["LOCAL_DATABASE_USERNAME"] %>
  password: <%= ENV["LOCAL_DATABASE_PASSWORD"] %>
  hostname: <%= ENV["DATABASE_HOSTNAME"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mokomukas_development

test:
  <<: *default
  database: mokomukas_test

production:
  <<: *default
  database: mokomukas_production
  username: <%= ENV["PROD_DATABASE_USERNAME"] %>
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>
